"""add email column

Revision ID: d99f4d9e89e5
Revises: a226b6dc3b55
Create Date: 2026-05-29 15:22:59.752458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99f4d9e89e5'
down_revision: Union[str, Sequence[str], None] = 'a226b6dc3b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "customers",
    sa.Column('email', sa.String(), nullable=True)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
